spring:
  datasource:
    url: jdbc:mysql://rm-bp1cjiazfe8207a61o.mysql.rds.aliyuncs.com:3306/double_report?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: Hello1234!
    driver-class-name: com.mysql.cj.jdbc.Driver